# Generated by Django 4.2.5 on 2023-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membrname', models.CharField(max_length=200)),
                ('membrimg', models.ImageField(upload_to='pics')),
                ('membrdesc', models.TextField()),
            ],
        ),
    ]
